### ISSUE TITLE
Bubble clustering

### ISSUE THREAD

**Issue by tomvaillant** [the-pudding/sleep-training#10]
Hey Matt, spent a couple hours trying different ways to cluster to force nodes. Started by trying understand the force clustering Observable code - but it's a bit too complex. Then tried using the [force-cluster npm package](https://github.com/ericsoco/d3-force-cluster?tab=readme-ov-file), which I think would get us there but:
- my force("cluster") is going to be competing with .force(x) and I'm not sure how to get these to work together
- the function I am using to cluster by position is likely incorrect.

```
`const clusterCenters = positions.map((position, index) => {
                const angle = (index / positions.length) * Math.PI * 2;
                const radius = Math.min(innerWidth, height) / 3;
                const x = Math.cos(angle) * radius + innerWidth / 2;
                const y = Math.sin(angle) * radius + height / 2;
                return { x, y };
            });`
```

**Comment by matthewfdaniels** [comment]
have you posted your code?

also what's the link to the observable code?

**Comment by tomvaillant** [comment]
I have! It's the D3 instructions page you linked in the feedback sorry, [here](https://observablehq.com/@d3/clustered-bubbles).

**Comment by matthewfdaniels** [comment]
I'm just not seeing this in your code. what component are you in?

<img width="1057" alt="image" src="https://github.com/tomvaillant/sleep-training/assets/2880174/2b98f0e1-7791-4857-835a-5059a625cb37">

**Comment by tomvaillant** [comment]
Gotcha! It looks like you're on an older version, can you git pull? I also just made some new pushes to main over the last hour (made some adjustments for feedback), you should see the clustering function commented out above the rerunSimulation function.

Bubbles.svelte is the right component.

**Comment by matthewfdaniels** [comment]
oh darn i was on my own branch from our pairing session. my bad!

**Comment by matthewfdaniels** [comment]
ok i got the observable example working in svelte. will replace it with your bubbles component in a branch!

**Comment by matthewfdaniels** [comment]
i just pushed a branch, refactoring your code a bit—hope it helps!

**Comment by tomvaillant** [comment]
WOW. That's a huge refactor. I'll dig into this and try to understand it, maybe on our next call you can walk me through a bit :) Thanks man.
