### ISSUE TITLE
images layout look to be broken here

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/sleep-training#21]
<img width="1006" alt="image" src="https://github.com/the-pudding/sleep-training/assets/2880174/e01912b8-3a4f-4764-b4c2-838e02799e99">

**Comment by tomvaillant** [comment]
Fixed this, but still having issues with the mobile version. An overflow: hidden; could work, but I can't get the Mosaic div to take the full width, over the article div padding.

**Comment by tomvaillant** [comment]
My fix has been removed, issue has returned here.
<img width="1077" alt="Screenshot 2024-07-02 at 12 42 03 PM" src="https://github.com/the-pudding/sleep-training/assets/34089393/477a6192-8fa3-48e8-abdc-cc6197cca6fb">
