### ISSUE TITLE
Legend still needs work in terms of clarifying bubble size (will think on this)

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/sleep-training#22]

**Comment by tomvaillant** [comment]
I passed both domain and range values to the legend, but the bubble sizing is an issue (and I'll need to format the domain numbers to be more friendly. Happy to do this with you.

<img width="383" alt="Screenshot 2024-07-02 at 12 29 28 PM" src="https://github.com/the-pudding/sleep-training/assets/34089393/334f1d12-89ff-42b9-900e-ca39ccbd41ca">
