### ISSUE TITLE
geojson is way too big—needs to be under 1MB

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/sleep-training#39]

**Comment by tomvaillant** [comment]
See you already did this one! Would love to know what you did, removed properties from features?

**Comment by matthewfdaniels** [comment]
you can use https://mapshaper.org/ to fix this, but i would recommend finding a way to do just a single geojson of land (no countries) and just positioning the circles over each country by having its lat/long hard coded in the data. right now, you're doing an awful lot of work to extract the coordinate from the geojson, and you only have a few countries to encode data for.

**Comment by matthewfdaniels** [comment]
FYI this is still at 5MB and ideally needs to get under 1MB; I'm looking at world-geojson2.json
