### ISSUE TITLE
contrast fails on scrolly color highlighting

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/sleep-training#48]
<img width="1249" alt="image" src="https://github.com/the-pudding/sleep-training/assets/2880174/cf1d76db-f576-4fa5-b29a-e6d1c8fe7957">

<img width="491" alt="image" src="https://github.com/the-pudding/sleep-training/assets/2880174/4f1be0d1-3231-456e-a250-5382cf6cb8d5">

**Comment by tomvaillant** [comment]
<img width="175" alt="Screenshot 2024-07-11 at 2 41 08 PM" src="https://github.com/the-pudding/sleep-training/assets/34089393/a81af858-076a-4e11-a7f4-a2bde761a937">
What do you think of this?
