### ISSUE TITLE
text link color fails contrast test

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/sleep-training#49]
<img width="865" alt="image" src="https://github.com/the-pudding/sleep-training/assets/2880174/349cd939-2071-4766-8e0a-635b662fdd55">

<img width="847" alt="image" src="https://github.com/the-pudding/sleep-training/assets/2880174/9efbe162-46fc-4a14-aa03-440510db61eb">

**Comment by tomvaillant** [comment]
Hope it's alright if I just re-active the font-weight: bolder; to pass the test.
