### ISSUE TITLE
Animations not rendering

### ISSUE THREAD

**Issue by tomvaillant** [the-pudding/sleep-training#5]
Ever since I moved the data formatting to +page.server.js, the animations are no longer rendering on screen. For the life of me I cannot figure out how to fix it. 

Example animations in Notification.svelte:
<div class="notification" in:fade={{ duration: 200, delay: index * 100 }} >

Or Mosaic.svelte
<div
        class="image-container"
        in:fly={{
          x: i % 2 === 0 ? -200 : 200,
          y: -200,
          duration: 1000,
          delay: i * 100,
          easing: cubicInOut
        }}
      >

**Comment by matthewfdaniels** [comment]
there's lots of ways to do this! easiest way would be to delay it from rendering

<img width="509" alt="image" src="https://github.com/tomvaillant/sleep-training/assets/2880174/6e1985d3-7454-4f57-88a7-470b187c3fae">

<img width="888" alt="image" src="https://github.com/tomvaillant/sleep-training/assets/2880174/23af29d1-43ce-4e38-ae8c-79456c3ab0b1">

**Comment by tomvaillant** [comment]
Thanks! Implemented this for HeroComments, but it won't solve the issue for the other instances of Notifications or Mosaic because they're all lower on the page and being rendered immediately on page load. But this is raised in the other ticket so I'll close this one!
