### ISSUE TITLE
library holdings: I think the legend is off for this based on your data files. I think we need a clearer title as well

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/sleep-training#51]
<img width="554" alt="image" src="https://github.com/the-pudding/sleep-training/assets/2880174/83429b93-2bbf-4877-8d11-2d0d9c3cdb08">

**Comment by tomvaillant** [comment]
Yes I'm having trouble with the radiusLegend component, I've tried fixing it 5 ways :( Maybe we can look at it in our call this week?
