### ISSUE TITLE
Cli.js error

### ISSUE THREAD

**Issue by tomvaillant** [the-pudding/sleep-training#63]
Since pulling the latest update I'm unable to run a local server, getting the following error:
`Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/buriedsignals/Code/svelte/sleep-training/node_modules/vite/dist/node/cli.js' imported from /Users/buriedsignals/Code/svelte/sleep-training/node_modules/vite/bin/vite.js`

**Comment by matthewfdaniels** [comment]
looks like you're missing the node module—try running npm i

**Comment by tomvaillant** [comment]
Yup I'd already done that, still got this error.
