### ISSUE TITLE
Span tags in title

### ISSUE THREAD

**Issue by tomvaillant** [the-pudding/sleep-training#64]
I think you mentioned this before, should I remove the span tags in the site title?
<img width="350" alt="Screenshot 2024-07-15 at 9 25 12 AM" src="https://github.com/user-attachments/assets/62ab7b4d-eaf7-47b9-a889-f00a5ca29b27">

**Comment by matthewfdaniels** [comment]
yes i believe i fixed this in my latest branch but you should make sure they are not appearing in the meta data
