### ISSUE TITLE
Mobile issues in ForceBubbles.svelte

### ISSUE THREAD

**Issue by tomvaillant** [the-pudding/sleep-training#66]
I won't be able to fix this responsiveness issue, really sorry :( 

<img width="394" alt="Screenshot 2024-07-15 at 3 03 30 PM" src="https://github.com/user-attachments/assets/71e5c74f-a241-4046-948d-abf5850c6ca7">
<img width="403" alt="Screenshot 2024-07-15 at 3 03 46 PM" src="https://github.com/user-attachments/assets/cd4483ce-7e04-4670-bff6-61079854a0af">

**Comment by matthewfdaniels** [comment]
on mobile, there's not a ton of screen real estate, so you'll likely want to position the tooltip constantly in the same place (at the top or bottom of the viz).

for the overlapping labels, you'll need to manually nudge these

**Comment by tomvaillant** [comment]
Thx for the tip! Glad you challenged me to do this one, managed it :)
