### ISSUE TITLE
links fail contrast test

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/sleep-training#68]
<img width="372" alt="image" src="https://github.com/user-attachments/assets/c26d7594-64ef-4ef9-8b8a-3baefccf9ab5">
<img width="876" alt="image" src="https://github.com/user-attachments/assets/c90efd8a-1934-4691-b1bd-10e625d74952">

**Comment by tomvaillant** [comment]
Fixed! Sorry, I was testing a lot of colours yesterday and slid 2px too far right in the color wheel.

<img width="797" alt="Screenshot 2024-07-16 at 10 16 14 AM" src="https://github.com/user-attachments/assets/18b90a21-e876-4d4b-89fb-e9f61da060d8">
