### ISSUE TITLE
issue with scrolling on mobile over the timeline and title overlap with chart

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/sleep-training#74]
<img width="341" alt="image" src="https://github.com/user-attachments/assets/9f1e577a-5e6d-4968-bf8f-16244cdc23ac">

**Comment by tomvaillant** [comment]
You might be on an older version of main, as I fixed this one yesterday by adding a width of 100% for the title at the top.

**Comment by matthewfdaniels** [comment]
I'm on staging—is the github.io link reflecting your latest?

**Comment by tomvaillant** [comment]
Oh staging might be missing a few tweaks (had some build issues yesterday), will try pushing now. But all of the other tickets are relevant.
