### ISSUE TITLE
Import and render HTML from copy doc

### ISSUE THREAD

**Issue by tomvaillant** [the-pudding/sleep-training#8]
Not sure how to import text as HTML from the GDoc, so that I can have hyperlinks and italics.

**Comment by matthewfdaniels** [comment]
If the string from your copy doc is called `text`, instead of `{text}` you'd do `{@html text}`

**Comment by tomvaillant** [comment]
Added this thanks, but HTML isn't being imported from the GDoc so it isn't available in the copy.json file.

**Comment by matthewfdaniels** [comment]
ah. you need to write out the html in the copy doc. so bold is <strong>hello</strong> and a link is:

`The most conclusive long-term study to date is a recent <a target=_blank href=https://google.com>randomized controlled</a> trial by Price et all on 326 infants which found no difference on any measure`

note that you shouldn't use quotes or apostrophes in the html tags. just write out the link attributes right after the equal sign.

**Comment by tomvaillant** [comment]
Sorry for not thinking of that :( Done! Thank you.
