### ISSUE TITLE
legend confusion

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/sleep-training#82]
some last minute feedback: I thought it would be fine, but folks were confused by the bubble sizes in the legend not matching the bubble sizes in the chart. it'll be hard for us to get them to match due to the circle packing layout, so something like this would work. I'll implement before launch assuming you're ok with it.

![image](https://github.com/user-attachments/assets/b4ab7842-7d94-4da9-b220-8eef1256dd00)

**Comment by tomvaillant** [comment]
Oh it's been completely re-done didn't see that! Had they seen my earlier version? The circles weren't sized perfectly but I think it was closer.
