### ISSUE TITLE
author bio

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/sleep-training#83]
can you send me a bio? here's an example:
https://pudding.cool/author/chris-dalla-riva/

you can list a social URL, a website URL, and an email address (all optional)

**Comment by tomvaillant** [comment]
Tom Vaillant is a video and visual journalist working on stories for the Pulitzer Center, NZZ, Grist and Tortoise. His <a href="https://www.nuanced.ch/" target="_blank">monthly newsletter Nuanced</a> decodes the tools and methods used to build popular visual stories. You can follow him on <a href="https://www.youtube.com/@_tomvaillant" target="_blank">Youtube</a> to watch his data-driven video investigations or on <a href="https://x.com/_tomvaillant" target="_blank">X</a>.
